eureka:
  instance:
    hostname: application
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://eureka-server:8761}/eureka/

server:
  tomcat:
    max-threads: 500 # Maximum amount of worker threads.
    min-spare-threads: 50 # Minimum amount of worker threads
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/test?useUnicode=true&characterEncoding=UTF8&useSSL=false&autoReconnect=true
    driver-classtester-name: com.mysql.jdbc.Driver
    username: tester
    password: 123456
    max-idle: 10
    min-idle: 5
    test-on-borrow: false
    time-between-eviction-runs-millis: 18800
    test-while-idle: true
    validation-query: SELECT 1
    hikari:
      minimum-idle: 0
  redis:
    host: redis
    port: 6379
    password:

  rabbitmq:
    host: rabbitmq
    #port: 15672
    username: guest
    password: guest
  http:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
redis:
  cache:
    expiration: 3601
ribbon:
  eager-load:
    enabled: true
    clients: authentication,basic-user-service
  Httpclient:
    enabled: true
  OkHttp:
    enabled: false
  ReadTimeout: 10000
  ConnectTimeout: 10000
  eureka:
    enabled: true

feign:
  hystrix:
    enabled: true
  okhttp:
    enabled: false
  httpclient:
    enabled: true
  client:
    config:
      feignName:
        connectTimeout: 30000
        readTimeout: 30000
  compression:
    request:
      enabled: true
    response:
      enabled: true
hystrix:
  threadpool:
    default:
      coreSize: 500
      maxQueueSize: 1000
      queueSizeRejectionThreshold: 800
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
