ignore:
  urls:
    - /**/*.css
    - /auth/**
eureka:
  instance:
    prefer-ip-address: true
    hostname: gateway
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://eureka-server:8761}/eureka/
